# Generated by Django 5.2.3 on 2025-06-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='playing_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='coaching_focus',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='coaching_style',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='playing_position',
            field=models.CharField(blank=True, choices=[('Striker', 'Striker'), ('Winger', 'Winger'), ('Midfielder', 'Midfielder'), ('Defender', 'Defender'), ('Goalkeeper', 'Goalkeeper')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('coach', 'Coach')], default='player', max_length=10),
            preserve_default=False,
        ),
    ]
