# Generated by Django 5.2.3 on 2025-06-18 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True)),
                ('position', models.CharField(choices=[('Striker', 'Striker'), ('Winger', 'Winger'), ('Midfield', 'Midfield'), ('Defender', 'Defender'), ('Goalkeeper', 'Goalkeeper'), ('General', 'General')], max_length=20)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
