# Generated by Django 5.2.3 on 2025-06-18 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('training_styles', models.TextField(blank=True)),
                ('skill_focus', models.CharField(blank=True, max_length=200)),
                ('socials', models.URLField(blank=True)),
                ('session_types', models.CharField(blank=True, max_length=200)),
                ('price_per_session', models.DecimalField(decimal_places=2, max_digits=6)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('availability', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
